//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsAndVotesSystem.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int CurrencyID { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<bool> Show { get; set; }
        public Nullable<int> Sort { get; set; }
        public string CurrencyNameEN { get; set; }
        public string ISO { get; set; }
        public string SymbolAR { get; set; }
        public string SymbolEN { get; set; }
        public Nullable<bool> ShowEN { get; set; }
        public Nullable<int> SortEN { get; set; }
        public Nullable<int> UserID_Add { get; set; }
        public Nullable<System.DateTime> Date_Add { get; set; }
        public Nullable<int> UserID_Edit { get; set; }
        public Nullable<System.DateTime> Date_Edit { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
