//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsAndVotesSystem.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailingList
    {
        public long MailingID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public int DeviceTypeID_Add { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Remove { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        public virtual Language Language { get; set; }
    }
}
