//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsAndVotesSystem.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> DeviceTypeID_Add { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string MessageSubject { get; set; }
        public string MessageConent { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public string Language { get; set; }
    
        public virtual DeviceType DeviceType { get; set; }
    }
}
