//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsAndVotesSystem.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Question_Answer_Values = new HashSet<Question_Answer_Values>();
            this.Questions_Comunities = new HashSet<Questions_Comunities>();
            this.User_Answers = new HashSet<User_Answers>();
        }
    
        public int Id { get; set; }
        public int PostId { get; set; }
        public int AnswerTypeId { get; set; }
        public string QuesetionTitle { get; set; }
        public string PhotoUrl { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<bool> IsRankeditorChoice { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> TotalAnswers { get; set; }
    
        public virtual Answer_Types Answer_Types { get; set; }
        public virtual Post_Info Post_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question_Answer_Values> Question_Answer_Values { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questions_Comunities> Questions_Comunities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Answers> User_Answers { get; set; }
    }
}
