//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsAndVotesSystem.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions_Comunities
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public int ComunitieId { get; set; }
        public Nullable<System.DateTime> AddingDate { get; set; }
    
        public virtual Community Community { get; set; }
        public virtual Question Question { get; set; }
    }
}
