//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsAndVotesSystem.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roleprimission
    {
        public int ID { get; set; }
        public string RoleId { get; set; }
        public int PageID { get; set; }
        public bool CanADD { get; set; }
        public bool CanUpdate { get; set; }
        public bool CanShow { get; set; }
        public bool CanDelete { get; set; }
        public bool CanSearch { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual AspNetRole AspNetRole { get; set; }
    }
}
