//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsAndVotesSystem.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteManagementSection
    {
        public int SiteManagementSectionID { get; set; }
        public int ID { get; set; }
        public string Photo { get; set; }
        public string PhotoAltAR { get; set; }
        public string PhotoAltEN { get; set; }
        public string TitleEN { get; set; }
        public string TitleAR { get; set; }
        public string SubTitleAR { get; set; }
        public string SubTitleEN { get; set; }
        public Nullable<bool> ShowEN { get; set; }
        public Nullable<bool> ShowAR { get; set; }
        public string URLEN { get; set; }
        public string URLAR { get; set; }
        public string URLTitleAR { get; set; }
        public string URLTitleEN { get; set; }
        public string SummaryAR { get; set; }
        public string SummaryEN { get; set; }
        public string DetailsEN { get; set; }
        public string DetailsAR { get; set; }
        public Nullable<int> UserID_Add { get; set; }
        public Nullable<System.DateTime> Date_Add { get; set; }
        public Nullable<int> UserID_Edit { get; set; }
        public Nullable<System.DateTime> Date_Edit { get; set; }
        public Nullable<int> SortAR { get; set; }
        public Nullable<int> SortEN { get; set; }
    
        public virtual SiteManagement SiteManagement { get; set; }
    }
}
