//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsAndVotesSystem.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteManagementType
    {
        public int SiteManagementTypeID { get; set; }
        public string TitleAR { get; set; }
        public string TitleEN { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> UserID_Add { get; set; }
        public Nullable<System.DateTime> Date_Add { get; set; }
        public Nullable<int> UserID_Edit { get; set; }
        public Nullable<System.DateTime> Date_Edit { get; set; }
        public string Routing { get; set; }
    }
}
