//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsAndVotesSystem.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialNetwork
    {
        public int SocialNetworkID { get; set; }
        public string URL { get; set; }
        public string Name { get; set; }
        public string NameEN { get; set; }
        public string Icon { get; set; }
        public string BgColor { get; set; }
        public string BgColorHover { get; set; }
        public string IconColor { get; set; }
        public string IconColorHover { get; set; }
        public Nullable<bool> ShowAR { get; set; }
        public Nullable<bool> ShowEN { get; set; }
        public Nullable<int> SortAR { get; set; }
        public Nullable<int> SortEN { get; set; }
        public string URLTitleAR { get; set; }
        public string URLTitleEN { get; set; }
        public Nullable<int> UserID_Add { get; set; }
        public Nullable<System.DateTime> Date_Add { get; set; }
        public Nullable<int> UserID_Edit { get; set; }
        public Nullable<System.DateTime> Date_Edit { get; set; }
    }
}
