//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsAndVotesSystem.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteInfoSmsAndNotificationStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebsiteInfoSmsAndNotificationStatu()
        {
            this.WebsiteInfoSmsAndNotifications = new HashSet<WebsiteInfoSmsAndNotification>();
        }
    
        public int WebsiteInfoSmsStatusID { get; set; }
        public string State { get; set; }
        public string StateEN { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> ShowSMS { get; set; }
        public Nullable<bool> ShowNotification { get; set; }
        public Nullable<int> UserID_Add { get; set; }
        public Nullable<System.DateTime> Date_Add { get; set; }
        public Nullable<int> UserID_Edit { get; set; }
        public Nullable<System.DateTime> Date_Edit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteInfoSmsAndNotification> WebsiteInfoSmsAndNotifications { get; set; }
    }
}
