//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsAndVotesSystem.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteInfoEmailSettingType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebsiteInfoEmailSettingType()
        {
            this.WebsiteInfoEmailSettings = new HashSet<WebsiteInfoEmailSetting>();
        }
    
        public int WebsiteInfoEmailSettingTypeID { get; set; }
        public string TitleDevelopment { get; set; }
        public Nullable<bool> Show { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> UserID_Add { get; set; }
        public Nullable<System.DateTime> Date_Add { get; set; }
        public Nullable<int> UserID_Edit { get; set; }
        public Nullable<System.DateTime> Date_Edit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteInfoEmailSetting> WebsiteInfoEmailSettings { get; set; }
    }
}
