//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsAndVotesSystem.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteInfoEmailSetting
    {
        public int WebsiteInfoEmailSettingID { get; set; }
        public Nullable<int> WebsiteInfoID { get; set; }
        public Nullable<int> WebsiteInfoEmailSettingTypeID { get; set; }
        public string TitleDevelopment { get; set; }
        public string Sender_Email { get; set; }
        public string Sender_EmailName { get; set; }
        public string Sender_EmailNameEN { get; set; }
        public string BCC_Emails { get; set; }
        public string Subject { get; set; }
        public string SubjectEN { get; set; }
        public string Title { get; set; }
        public string TitleEN { get; set; }
        public string EmailFileName { get; set; }
        public string EmailFileNameEN { get; set; }
        public string MessageSuccess { get; set; }
        public string MessageSuccessEN { get; set; }
        public string MessageFailed { get; set; }
        public string MessageFailedEN { get; set; }
        public Nullable<int> UserID_Add { get; set; }
        public Nullable<System.DateTime> Date_Add { get; set; }
        public Nullable<int> UserID_Edit { get; set; }
        public Nullable<System.DateTime> Date_Edit { get; set; }
    
        public virtual WebsiteInfo WebsiteInfo { get; set; }
        public virtual WebsiteInfoEmailSettingType WebsiteInfoEmailSettingType { get; set; }
    }
}
