//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsAndVotesSystem.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebsiteInfo()
        {
            this.WebsiteInfoEmailSettings = new HashSet<WebsiteInfoEmailSetting>();
            this.WebsiteInfoSmsAndNotifications = new HashSet<WebsiteInfoSmsAndNotification>();
        }
    
        public int WebsiteInfoID { get; set; }
        public string WebsiteNameEN { get; set; }
        public string WebsiteNameAR { get; set; }
        public string AddressEN { get; set; }
        public string AddressAR { get; set; }
        public string Hotline { get; set; }
        public string Phone { get; set; }
        public string WorkTimeAR { get; set; }
        public string WorkTimeEN { get; set; }
        public string Domain { get; set; }
        public string ConactEmail { get; set; }
        public string Logo { get; set; }
        public string LogoFooter { get; set; }
        public string Map { get; set; }
        public string SeoScript { get; set; }
        public string FacebookPage { get; set; }
        public string SloganAR { get; set; }
        public string SloganEN { get; set; }
        public Nullable<int> UserID_Add { get; set; }
        public Nullable<System.DateTime> Date_Add { get; set; }
        public Nullable<int> UserID_Edit { get; set; }
        public Nullable<System.DateTime> Date_Edit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteInfoEmailSetting> WebsiteInfoEmailSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteInfoSmsAndNotification> WebsiteInfoSmsAndNotifications { get; set; }
    }
}
