//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsAndVotesSystem.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteInfoSmsAndNotification
    {
        public int WebsiteInfoSmsID { get; set; }
        public int WebsiteInfoID { get; set; }
        public int WebsiteInfoSmsStatusID { get; set; }
        public string MessageTextAR { get; set; }
        public string MessageTextEN { get; set; }
        public string NotificationTitle { get; set; }
        public string NotificationTitleEN { get; set; }
        public string NotificationDetails { get; set; }
        public string NotificationDetailsEN { get; set; }
        public string NotificationPhoto { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> UserID_Add { get; set; }
        public Nullable<System.DateTime> Date_Add { get; set; }
        public Nullable<int> UserID_Edit { get; set; }
        public Nullable<System.DateTime> Date_Edit { get; set; }
    
        public virtual WebsiteInfo WebsiteInfo { get; set; }
        public virtual WebsiteInfoSmsAndNotificationStatu WebsiteInfoSmsAndNotificationStatu { get; set; }
    }
}
